package com.techlife.kockit.core.network.annotation

@MustBeDocumented
@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.FUNCTION)
annotation class ApiLog(val service: String)

object ApiServices {
    const val AUTH_STUDENT_REGISTER = "AUTH_STUDENT_REGISTER"
    const val AUTH_GOOGLE_REGISTER = "AUTH_GOOGLE_REGISTER"
    const val AUTH_LOGIN_NICKNAME = "AUTH_LOGIN_NICKNAME"
    const val AUTH_LOGIN_SMS_REQUEST = "AUTH_LOGIN_SMS_REQUEST"
    const val AUTH_LOGIN_SMS_VERIFY = "AUTH_LOGIN_SMS_VERIFY"
    const val AUTH_LOGIN_GOOGLE = "AUTH_LOGIN_GOOGLE"
    const val AUTH_LOGIN_TECHPASS = "AUTH_LOGIN_TECHPASS"
    const val AUTH_TOKEN_REFRESH = "AUTH_TOKEN_REFRESH"
    const val AUTH_LOGOUT = "AUTH_LOGOUT"
    const val AUTH_SMS_SEND_CODE = "AUTH_SMS_SEND_CODE"
    const val AUTH_SMS_VERIFY_CODE = "AUTH_SMS_VERIFY_CODE"
    const val LESSON_LIST = "LESSON_LIST"
    const val PROVINCE_LIST = "PROVINCE_LIST"
    const val DISTRICT_LIST = "DISTRICT_LIST"
    const val YO_BILIM_LIST = "YO_BILIM_LIST"
    const val YO_UNIVERSITE_LIST = "YO_UNIVERSITE_LIST"
    const val YO_FAKULTE_LIST = "YO_FAKULTE_LIST"
    const val YO_BOLUM_LIST = "YO_BOLUM_LIST"
    const val OGRENCI_GET = "OGRENCI_GET"
    const val OGRENCI_CALISMA_TAKVIMI_UPDATE = "OGRENCI_CALISMA_TAKVIMI_UPDATE"
    const val OGRENCI_HEDEF_CREATE = "OGRENCI_HEDEF_CREATE"
    const val KULLANICI_UPDATE = "KULLANICI_UPDATE"
    const val PUAN_SIRALAMA_PUANDAN = "PUAN_SIRALAMA_PUANDAN"
    const val PUAN_SIRALAMA_SIRALAMADAN = "PUAN_SIRALAMA_SIRALAMADAN"
}
