package com.techlife.kockit.feature.goalsetup

import com.techlife.kockit.domain.onboarding.model.University
import com.techlife.kockit.domain.onboarding.model.UniversityType

object GoalSetupUniversityCatalog {
    val regions = listOf(
        "Marmara",
        "Ege",
        "İç Anadolu",
        "Akdeniz",
        "Karadeniz",
        "Doğu Anadolu",
        "Güneydoğu Anadolu"
    )

    val universities = listOf(
        // Marmara — İstanbul
        University("u001", "Boğaziçi Üniversitesi", "İstanbul", "Marmara", UniversityType.DEVLET),
        University("u002", "İstanbul Teknik Üniversitesi", "İstanbul", "Marmara", UniversityType.DEVLET),
        University("u003", "Marmara Üniversitesi", "İstanbul", "Marmara", UniversityType.DEVLET),
        University("u004", "İstanbul Üniversitesi", "İstanbul", "Marmara", UniversityType.DEVLET),
        University("u005", "Yıldız Teknik Üniversitesi", "İstanbul", "Marmara", UniversityType.DEVLET),
        University("u006", "Galatasaray Üniversitesi", "İstanbul", "Marmara", UniversityType.DEVLET),
        University("u007", "Mimar Sinan Güzel Sanatlar Üniversitesi", "İstanbul", "Marmara", UniversityType.DEVLET),
        University("u008", "İstanbul Medeniyet Üniversitesi", "İstanbul", "Marmara", UniversityType.DEVLET),
        University("u009", "Koç Üniversitesi", "İstanbul", "Marmara", UniversityType.VAKIF),
        University("u010", "Sabancı Üniversitesi", "İstanbul", "Marmara", UniversityType.VAKIF),
        University("u011", "İstanbul Bilgi Üniversitesi", "İstanbul", "Marmara", UniversityType.VAKIF),
        University("u012", "Bahçeşehir Üniversitesi", "İstanbul", "Marmara", UniversityType.VAKIF),
        University("u013", "Kadir Has Üniversitesi", "İstanbul", "Marmara", UniversityType.VAKIF),
        University("u014", "Özyeğin Üniversitesi", "İstanbul", "Marmara", UniversityType.VAKIF),
        University("u015", "Medipol Üniversitesi", "İstanbul", "Marmara", UniversityType.VAKIF),
        University("u016", "Altınbaş Üniversitesi", "İstanbul", "Marmara", UniversityType.OZEL),
        University("u017", "İstinye Üniversitesi", "İstanbul", "Marmara", UniversityType.OZEL),
        University("u018", "Nişantaşı Üniversitesi", "İstanbul", "Marmara", UniversityType.OZEL),

        // Marmara — diğer iller
        University("u019", "Bursa Uludağ Üniversitesi", "Bursa", "Marmara", UniversityType.DEVLET),
        University("u020", "Bursa Teknik Üniversitesi", "Bursa", "Marmara", UniversityType.DEVLET),
        University("u021", "Bursa Orhangazi Üniversitesi", "Bursa", "Marmara", UniversityType.OZEL),
        University("u022", "Kocaeli Üniversitesi", "Kocaeli", "Marmara", UniversityType.DEVLET),
        University("u023", "Gebze Teknik Üniversitesi", "Kocaeli", "Marmara", UniversityType.DEVLET),
        University("u024", "Sakarya Üniversitesi", "Sakarya", "Marmara", UniversityType.DEVLET),
        University("u025", "Sakarya Uygulamalı Bilimler Üniversitesi", "Sakarya", "Marmara", UniversityType.DEVLET),
        University("u026", "Tekirdağ Namık Kemal Üniversitesi", "Tekirdağ", "Marmara", UniversityType.DEVLET),
        University("u027", "Trakya Üniversitesi", "Edirne", "Marmara", UniversityType.DEVLET),
        University("u028", "Balıkesir Üniversitesi", "Balıkesir", "Marmara", UniversityType.DEVLET),
        University("u029", "Bandırma Onyedi Eylül Üniversitesi", "Balıkesir", "Marmara", UniversityType.DEVLET),
        University("u030", "Çanakkale Onsekiz Mart Üniversitesi", "Çanakkale", "Marmara", UniversityType.DEVLET),
        University("u031", "Yalova Üniversitesi", "Yalova", "Marmara", UniversityType.DEVLET),
        University("u032", "Düzce Üniversitesi", "Düzce", "Marmara", UniversityType.DEVLET),
        University("u033", "Bolu Abant İzzet Baysal Üniversitesi", "Bolu", "Marmara", UniversityType.DEVLET),

        // Ege
        University("u034", "Ege Üniversitesi", "İzmir", "Ege", UniversityType.DEVLET),
        University("u035", "Dokuz Eylül Üniversitesi", "İzmir", "Ege", UniversityType.DEVLET),
        University("u036", "İzmir Yüksek Teknoloji Enstitüsü", "İzmir", "Ege", UniversityType.DEVLET),
        University("u037", "İzmir Katip Çelebi Üniversitesi", "İzmir", "Ege", UniversityType.DEVLET),
        University("u038", "İzmir Bakırçay Üniversitesi", "İzmir", "Ege", UniversityType.DEVLET),
        University("u039", "Yaşar Üniversitesi", "İzmir", "Ege", UniversityType.VAKIF),
        University("u040", "İzmir Ekonomi Üniversitesi", "İzmir", "Ege", UniversityType.VAKIF),
        University("u041", "İzmir Tınaztepe Üniversitesi", "İzmir", "Ege", UniversityType.OZEL),
        University("u042", "Manisa Celal Bayar Üniversitesi", "Manisa", "Ege", UniversityType.DEVLET),
        University("u043", "Aydın Adnan Menderes Üniversitesi", "Aydın", "Ege", UniversityType.DEVLET),
        University("u044", "Muğla Sıtkı Koçman Üniversitesi", "Muğla", "Ege", UniversityType.DEVLET),
        University("u045", "Pamukkale Üniversitesi", "Denizli", "Ege", UniversityType.DEVLET),
        University("u046", "Uşak Üniversitesi", "Uşak", "Ege", UniversityType.DEVLET),
        University("u047", "Afyon Kocatepe Üniversitesi", "Afyonkarahisar", "Ege", UniversityType.DEVLET),
        University("u048", "Kütahya Dumlupınar Üniversitesi", "Kütahya", "Ege", UniversityType.DEVLET),

        // İç Anadolu
        University("u049", "Orta Doğu Teknik Üniversitesi", "Ankara", "İç Anadolu", UniversityType.DEVLET),
        University("u050", "Hacettepe Üniversitesi", "Ankara", "İç Anadolu", UniversityType.DEVLET),
        University("u051", "Ankara Üniversitesi", "Ankara", "İç Anadolu", UniversityType.DEVLET),
        University("u052", "Gazi Üniversitesi", "Ankara", "İç Anadolu", UniversityType.DEVLET),
        University("u053", "Başkent Üniversitesi", "Ankara", "İç Anadolu", UniversityType.VAKIF),
        University("u054", "Bilkent Üniversitesi", "Ankara", "İç Anadolu", UniversityType.VAKIF),
        University("u055", "Atılım Üniversitesi", "Ankara", "İç Anadolu", UniversityType.VAKIF),
        University("u056", "Çankaya Üniversitesi", "Ankara", "İç Anadolu", UniversityType.VAKIF),
        University("u057", "TED Üniversitesi", "Ankara", "İç Anadolu", UniversityType.OZEL),
        University("u058", "Ufuk Üniversitesi", "Ankara", "İç Anadolu", UniversityType.OZEL),
        University("u059", "Selçuk Üniversitesi", "Konya", "İç Anadolu", UniversityType.DEVLET),
        University("u060", "Konya Teknik Üniversitesi", "Konya", "İç Anadolu", UniversityType.DEVLET),
        University("u061", "Necmettin Erbakan Üniversitesi", "Konya", "İç Anadolu", UniversityType.DEVLET),
        University("u062", "Karamanoğlu Mehmetbey Üniversitesi", "Karaman", "İç Anadolu", UniversityType.DEVLET),
        University("u063", "Erciyes Üniversitesi", "Kayseri", "İç Anadolu", UniversityType.DEVLET),
        University("u064", "Abdullah Gül Üniversitesi", "Kayseri", "İç Anadolu", UniversityType.DEVLET),
        University("u065", "Anadolu Üniversitesi", "Eskişehir", "İç Anadolu", UniversityType.DEVLET),
        University("u066", "Eskişehir Osmangazi Üniversitesi", "Eskişehir", "İç Anadolu", UniversityType.DEVLET),
        University("u067", "Eskişehir Teknik Üniversitesi", "Eskişehir", "İç Anadolu", UniversityType.DEVLET),
        University("u068", "Sivas Cumhuriyet Üniversitesi", "Sivas", "İç Anadolu", UniversityType.DEVLET),
        University("u069", "Nevşehir Hacı Bektaş Veli Üniversitesi", "Nevşehir", "İç Anadolu", UniversityType.DEVLET),
        University("u070", "Aksaray Üniversitesi", "Aksaray", "İç Anadolu", UniversityType.DEVLET),
        University("u071", "Kırıkkale Üniversitesi", "Kırıkkale", "İç Anadolu", UniversityType.DEVLET),
        University("u072", "Kırşehir Ahi Evran Üniversitesi", "Kırşehir", "İç Anadolu", UniversityType.DEVLET),
        University("u073", "Çankırı Karatekin Üniversitesi", "Çankırı", "İç Anadolu", UniversityType.DEVLET),
        University("u074", "Yozgat Bozok Üniversitesi", "Yozgat", "İç Anadolu", UniversityType.DEVLET),

        // Akdeniz
        University("u075", "Akdeniz Üniversitesi", "Antalya", "Akdeniz", UniversityType.DEVLET),
        University("u076", "Alanya Alaaddin Keykubat Üniversitesi", "Antalya", "Akdeniz", UniversityType.DEVLET),
        University("u077", "Antalya Bilim Üniversitesi", "Antalya", "Akdeniz", UniversityType.VAKIF),
        University("u078", "Çukurova Üniversitesi", "Adana", "Akdeniz", UniversityType.DEVLET),
        University("u079", "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi", "Adana", "Akdeniz", UniversityType.DEVLET),
        University("u080", "Mersin Üniversitesi", "Mersin", "Akdeniz", UniversityType.DEVLET),
        University("u081", "Tarsus Üniversitesi", "Mersin", "Akdeniz", UniversityType.DEVLET),
        University("u082", "Hatay Mustafa Kemal Üniversitesi", "Hatay", "Akdeniz", UniversityType.DEVLET),
        University("u083", "İskenderun Teknik Üniversitesi", "Hatay", "Akdeniz", UniversityType.DEVLET),
        University("u084", "Isparta Uygulamalı Bilimler Üniversitesi", "Isparta", "Akdeniz", UniversityType.DEVLET),
        University("u085", "Süleyman Demirel Üniversitesi", "Isparta", "Akdeniz", UniversityType.DEVLET),
        University("u086", "Burdur Mehmet Akif Ersoy Üniversitesi", "Burdur", "Akdeniz", UniversityType.DEVLET),
        University("u087", "Kahramanmaraş Sütçü İmam Üniversitesi", "Kahramanmaraş", "Akdeniz", UniversityType.DEVLET),
        University("u088", "Kahramanmaraş İstiklal Üniversitesi", "Kahramanmaraş", "Akdeniz", UniversityType.DEVLET),
        University("u089", "Osmaniye Korkut Ata Üniversitesi", "Osmaniye", "Akdeniz", UniversityType.DEVLET),

        // Karadeniz
        University("u090", "Karadeniz Teknik Üniversitesi", "Trabzon", "Karadeniz", UniversityType.DEVLET),
        University("u091", "Trabzon Üniversitesi", "Trabzon", "Karadeniz", UniversityType.DEVLET),
        University("u092", "Ondokuz Mayıs Üniversitesi", "Samsun", "Karadeniz", UniversityType.DEVLET),
        University("u093", "Samsun Üniversitesi", "Samsun", "Karadeniz", UniversityType.DEVLET),
        University("u094", "Recep Tayyip Erdoğan Üniversitesi", "Rize", "Karadeniz", UniversityType.DEVLET),
        University("u095", "Ordu Üniversitesi", "Ordu", "Karadeniz", UniversityType.DEVLET),
        University("u096", "Giresun Üniversitesi", "Giresun", "Karadeniz", UniversityType.DEVLET),
        University("u097", "Bayburt Üniversitesi", "Bayburt", "Karadeniz", UniversityType.DEVLET),
        University("u098", "Gümüşhane Üniversitesi", "Gümüşhane", "Karadeniz", UniversityType.DEVLET),
        University("u099", "Zonguldak Bülent Ecevit Üniversitesi", "Zonguldak", "Karadeniz", UniversityType.DEVLET),
        University("u100", "Karabük Üniversitesi", "Karabük", "Karadeniz", UniversityType.DEVLET),
        University("u101", "Bartın Üniversitesi", "Bartın", "Karadeniz", UniversityType.DEVLET),
        University("u102", "Kastamonu Üniversitesi", "Kastamonu", "Karadeniz", UniversityType.DEVLET),
        University("u103", "Sinop Üniversitesi", "Sinop", "Karadeniz", UniversityType.DEVLET),
        University("u104", "Amasya Üniversitesi", "Amasya", "Karadeniz", UniversityType.DEVLET),
        University("u105", "Tokat Gaziosmanpaşa Üniversitesi", "Tokat", "Karadeniz", UniversityType.DEVLET),
        University("u106", "Çorum Hitit Üniversitesi", "Çorum", "Karadeniz", UniversityType.DEVLET),
        University("u107", "Artvin Çoruh Üniversitesi", "Artvin", "Karadeniz", UniversityType.DEVLET),

        // Doğu Anadolu
        University("u108", "Atatürk Üniversitesi", "Erzurum", "Doğu Anadolu", UniversityType.DEVLET),
        University("u109", "Erzurum Teknik Üniversitesi", "Erzurum", "Doğu Anadolu", UniversityType.DEVLET),
        University("u110", "Fırat Üniversitesi", "Elazığ", "Doğu Anadolu", UniversityType.DEVLET),
        University("u111", "İnönü Üniversitesi", "Malatya", "Doğu Anadolu", UniversityType.DEVLET),
        University("u112", "Malatya Turgut Özal Üniversitesi", "Malatya", "Doğu Anadolu", UniversityType.DEVLET),
        University("u113", "Van Yüzüncü Yıl Üniversitesi", "Van", "Doğu Anadolu", UniversityType.DEVLET),
        University("u114", "Erzincan Binali Yıldırım Üniversitesi", "Erzincan", "Doğu Anadolu", UniversityType.DEVLET),
        University("u115", "Ağrı İbrahim Çeçen Üniversitesi", "Ağrı", "Doğu Anadolu", UniversityType.DEVLET),
        University("u116", "Kafkas Üniversitesi", "Kars", "Doğu Anadolu", UniversityType.DEVLET),
        University("u117", "Ardahan Üniversitesi", "Ardahan", "Doğu Anadolu", UniversityType.DEVLET),
        University("u118", "Iğdır Üniversitesi", "Iğdır", "Doğu Anadolu", UniversityType.DEVLET),
        University("u119", "Bingöl Üniversitesi", "Bingöl", "Doğu Anadolu", UniversityType.DEVLET),
        University("u120", "Muş Alparslan Üniversitesi", "Muş", "Doğu Anadolu", UniversityType.DEVLET),
        University("u121", "Bitlis Eren Üniversitesi", "Bitlis", "Doğu Anadolu", UniversityType.DEVLET),
        University("u122", "Tunceli Munzur Üniversitesi", "Tunceli", "Doğu Anadolu", UniversityType.DEVLET),

        // Güneydoğu Anadolu
        University("u123", "Dicle Üniversitesi", "Diyarbakır", "Güneydoğu Anadolu", UniversityType.DEVLET),
        University("u124", "Harran Üniversitesi", "Şanlıurfa", "Güneydoğu Anadolu", UniversityType.DEVLET),
        University("u125", "Gaziantep Üniversitesi", "Gaziantep", "Güneydoğu Anadolu", UniversityType.DEVLET),
        University("u126", "Gaziantep İslam Bilim ve Teknoloji Üniversitesi", "Gaziantep", "Güneydoğu Anadolu", UniversityType.DEVLET),
        University("u127", "Hasan Kalyoncu Üniversitesi", "Gaziantep", "Güneydoğu Anadolu", UniversityType.VAKIF),
        University("u128", "Mardin Artuklu Üniversitesi", "Mardin", "Güneydoğu Anadolu", UniversityType.DEVLET),
        University("u129", "Batman Üniversitesi", "Batman", "Güneydoğu Anadolu", UniversityType.DEVLET),
        University("u130", "Siirt Üniversitesi", "Siirt", "Güneydoğu Anadolu", UniversityType.DEVLET),
        University("u131", "Şırnak Üniversitesi", "Şırnak", "Güneydoğu Anadolu", UniversityType.DEVLET),
        University("u132", "Kilis 7 Aralık Üniversitesi", "Kilis", "Güneydoğu Anadolu", UniversityType.DEVLET),
        University("u133", "Adıyaman Üniversitesi", "Adıyaman", "Güneydoğu Anadolu", UniversityType.DEVLET)
    )

    val cities: List<String> = universities.map { it.city }.distinct().sorted()
}
