package com.techlife.kockit.feature.goalsetup

import com.techlife.kockit.domain.onboarding.model.Department

object GoalSetupDepartmentCatalog {
    val departments = listOf(
        Department("d01", "Bilgisayar Mühendisliği"),
        Department("d02", "Yazılım Mühendisliği"),
        Department("d03", "Elektrik-Elektronik Mühendisliği"),
        Department("d04", "Elektronik Mühendisliği"),
        Department("d05", "Endüstri Mühendisliği"),
        Department("d06", "Makine Mühendisliği"),
        Department("d07", "İnşaat Mühendisliği"),
        Department("d08", "Mimarlık"),
        Department("d09", "Şehir ve Bölge Planlama"),
        Department("d10", "İç Mimarlık"),
        Department("d11", "Peyzaj Mimarlığı"),
        Department("d12", "Biyomedikal Mühendisliği"),
        Department("d13", "Mekatronik Mühendisliği"),
        Department("d14", "Enerji Sistemleri Mühendisliği"),
        Department("d15", "Gıda Mühendisliği"),
        Department("d16", "Kimya Mühendisliği"),
        Department("d17", "Metalurji ve Malzeme Mühendisliği"),
        Department("d18", "Çevre Mühendisliği"),
        Department("d19", "Harita Mühendisliği"),
        Department("d20", "Jeoloji Mühendisliği"),
        Department("d21", "Maden Mühendisliği"),
        Department("d22", "Petrol ve Doğalgaz Mühendisliği"),
        Department("d23", "Uçak Mühendisliği"),
        Department("d24", "Uzay Mühendisliği"),
        Department("d25", "Gemi İnşaatı ve Denizcilik Mühendisliği"),
        Department("d26", "Tıp"),
        Department("d27", "Diş Hekimliği"),
        Department("d28", "Eczacılık"),
        Department("d29", "Hemşirelik"),
        Department("d30", "Fizyoterapi ve Rehabilitasyon"),
        Department("d31", "Beslenme ve Diyetetik"),
        Department("d32", "Veterinerlik"),
        Department("d33", "Hukuk"),
        Department("d34", "Psikoloji"),
        Department("d35", "Sosyoloji"),
        Department("d36", "Tarih"),
        Department("d37", "Coğrafya"),
        Department("d38", "Felsefe"),
        Department("d39", "Siyaset Bilimi ve Kamu Yönetimi"),
        Department("d40", "Uluslararası İlişkiler"),
        Department("d41", "İktisat"),
        Department("d42", "İşletme"),
        Department("d43", "Maliye"),
        Department("d44", "Ekonometri"),
        Department("d45", "Bankacılık ve Finans"),
        Department("d46", "Lojistik Yönetimi"),
        Department("d47", "Pazarlama"),
        Department("d48", "İnsan Kaynakları Yönetimi"),
        Department("d49", "Turizm İşletmeciliği"),
        Department("d50", "Gastronomi ve Mutfak Sanatları"),
        Department("d51", "Türk Dili ve Edebiyatı"),
        Department("d52", "İngiliz Dili ve Edebiyatı"),
        Department("d53", "Amerikan Kültürü ve Edebiyatı"),
        Department("d54", "Arkeoloji"),
        Department("d55", "Sanat Tarihi"),
        Department("d56", "Grafik Tasarım"),
        Department("d57", "Görsel İletişim Tasarımı"),
        Department("d58", "Sinema ve Televizyon"),
        Department("d59", "Halkla İlişkiler ve Tanıtım"),
        Department("d60", "Radyo, Televizyon ve Sinema"),
        Department("d61", "Müzik"),
        Department("d62", "Resim"),
        Department("d63", "Seramik ve Cam"),
        Department("d64", "Matematik"),
        Department("d65", "Fizik"),
        Department("d66", "Kimya"),
        Department("d67", "Biyoloji"),
        Department("d68", "Moleküler Biyoloji ve Genetik"),
        Department("d69", "İstatistik"),
        Department("d70", "Astronomi ve Uzay Bilimleri"),
        Department("d71", "Öğretmenlik Programları"),
        Department("d72", "Rehberlik ve Psikolojik Danışmanlık"),
        Department("d73", "Okul Öncesi Öğretmenliği"),
        Department("d74", "Sınıf Öğretmenliği"),
        Department("d75", "Matematik Öğretmenliği"),
        Department("d76", "Fen Bilgisi Öğretmenliği"),
        Department("d77", "Türkçe Öğretmenliği"),
        Department("d78", "İngilizce Öğretmenliği"),
        Department("d79", "Ziraat Mühendisliği"),
        Department("d80", "Orman Mühendisliği"),
        Department("d81", "Su Ürünleri Mühendisliği"),
        Department("d82", "İlahiyat"),
        Department("d83", "Sosyal Hizmet"),
        Department("d84", "Çalışma Ekonomisi ve Endüstri İlişkileri"),
        Department("d85", "Yönetim Bilişim Sistemleri"),
        Department("d86", "Bilgi ve Belge Yönetimi"),
        Department("d87", "Güvenlik Bilimleri"),
        Department("d88", "Pilotaj"),
        Department("d89", "Deniz Ulaştırma İşletme Mühendisliği"),
        Department("d90", "Otomotiv Mühendisliği")
    )
}
